-- MySQL Script generated by MySQL Workbench
-- 02/28/17 09:10:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema precise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema precise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `precise` DEFAULT CHARACTER SET utf8 ;
USE `precise` ;

-- -----------------------------------------------------
-- Table `precise`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`client` (
  `id_client` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type_document_id` INT NULL,
  `document_id` INT NULL,
  `web_site` VARCHAR(45) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `precise`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`project` (
  `id_project` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `value_estatimate_total` VARCHAR(45) NULL,
  `time_estimate_total` VARCHAR(45) NULL,
  PRIMARY KEY (`id_project`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `precise`.`client_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`client_project` (
  `id_client_project` INT(11) NOT NULL AUTO_INCREMENT,
  `id_project` INT(11) NOT NULL,
  `id_client` INT(11) NOT NULL,
  PRIMARY KEY (`id_client_project`),
  INDEX `client_idx` (`id_client` ASC),
  INDEX `project_idx` (`id_project` ASC),
  CONSTRAINT `fk_client_project_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `precise`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_project_project`
    FOREIGN KEY (`id_project`)
    REFERENCES `precise`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `precise`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`rol` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `precise`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`task` (
  `id_task` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `decription` VARCHAR(45) NULL DEFAULT NULL,
  `time` TIME NULL,
  `fase` VARCHAR(45) NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id_task`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `precise`.`task_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`task_project` (
  `id_task_project` INT(11) NOT NULL AUTO_INCREMENT,
  `id_project` INT(11) NOT NULL,
  `id_task` INT(11) NOT NULL,
  PRIMARY KEY (`id_task_project`),
  INDEX `project_idx` (`id_project` ASC),
  INDEX `task_idx` (`id_task` ASC),
  CONSTRAINT `fk_task_project_project`
    FOREIGN KEY (`id_project`)
    REFERENCES `precise`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_project_task`
    FOREIGN KEY (`id_task`)
    REFERENCES `precise`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `precise`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `recovery` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `precise`.`user_data_parameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`user_data_parameter` (
  `id_user_data_parameter` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id_user_data_parameter`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `precise`.`user_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`user_data` (
  `id_user_data` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_user_data_parameter` INT(11) NOT NULL,
  `value` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id_user_data`),
  INDEX `fk_user_data_user1_idx` (`id_user` ASC),
  INDEX `fk_user_data_user_data_parameter1_idx` (`id_user_data_parameter` ASC),
  CONSTRAINT `fk_user_data_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `precise`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_data_user_data_parameter1`
    FOREIGN KEY (`id_user_data_parameter`)
    REFERENCES `precise`.`user_data_parameter` (`id_user_data_parameter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `precise`.`user_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`user_project` (
  `id_user_project` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_project` INT NOT NULL,
  PRIMARY KEY (`id_user_project`),
  INDEX `fk_user_project_user_idx` (`id_user` ASC),
  INDEX `fk_user_project_project_idx` (`id_project` ASC),
  CONSTRAINT `fk_user_project_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `precise`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_project_project`
    FOREIGN KEY (`id_project`)
    REFERENCES `precise`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `precise`.`user_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`user_rol` (
  `id_user_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_rol` INT(11) NOT NULL,
  PRIMARY KEY (`id_user_rol`),
  INDEX `fk_user_rol_user_idx` (`id_user` ASC),
  INDEX `fk_user_rol_rol1_idx` (`id_rol` ASC),
  CONSTRAINT `fk_user_rol_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `precise`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rol_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `precise`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `precise`.`user_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precise`.`user_task` (
  `id_user_task` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_task` INT(11) NOT NULL,
  PRIMARY KEY (`id_user_task`),
  INDEX `user_idx` (`id_user` ASC),
  INDEX `task_idx` (`id_task` ASC),
  CONSTRAINT `fk_user_task_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `precise`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_task_task`
    FOREIGN KEY (`id_task`)
    REFERENCES `precise`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
